version: '3.4'

services:
  hrm.interview.apilayer:
    image: ${DOCKER_REGISTRY-}hrminterviewapilayer
    ports:
       - "7291:80"
    build:
      context: .
      dockerfile: Hrm.Interview.APILayer/Dockerfile

  hrm.recruiting.apilayer:
    image: ${DOCKER_REGISTRY-}hrmrecruitingapilayer
    ports:
       - "7292:80"
    build:
      context: .
      dockerfile: Hrm.Recruiting.APILayer/Dockerfile


  hrm.onboard.apilayer:
    image: ${DOCKER_REGISTRY-}hrmonboardapilayer
    ports:
       - "7293:80"
    build:
      context: .
      dockerfile: Hrm.Onboard.APILayer/Dockerfile


  hrm.authentication.apilayer:
    image: ${DOCKER_REGISTRY-}hrmauthenticationapilayer
    ports:
       - "7294:80"
    build:
      context: .
      dockerfile: Hrm.Authentication.APILayer/Dockerfile

