version: '3.4'

services:
  hrm.interview.apilayer:
    image: ${DOCKER_REGISTRY-}hrminterviewapilayer
    hostname: "interviewApiGateway"
    build:
      context: .
      dockerfile: Hrm.Interview.APILayer/Dockerfile

  hrm.recruiting.apilayer:
    image: ${DOCKER_REGISTRY-}hrmrecruitingapilayer
    hostname: "recruitingApiGateway"
    build:
      context: .
      dockerfile: Hrm.Recruiting.APILayer/Dockerfile


  hrm.onboard.apilayer:
    image: ${DOCKER_REGISTRY-}hrmonboardapilayer
    hostname: "onboardApiGateway"
    build:
      context: .
      dockerfile: Hrm.Onboard.APILayer/Dockerfile


  hrm.authentication.apilayer:
    image: ${DOCKER_REGISTRY-}hrmauthenticationapilayer
    hostname: "authenticationApiGateway"
    build:
      context: .
      dockerfile: Hrm.Authentication.APILayer/Dockerfile


  apigatewaylayer:
    image: ${DOCKER_REGISTRY-}apigatewaylayer
    build:
      context: .
      dockerfile: APIGatewayLayer/Dockerfile
    ports:
        - "7292:80"
